// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysDictData is the golang structure for table sys_dict_data.
type SysDictData struct {
	DictCode  int64       `orm:"dict_code,primary" json:"dictCode"`  // 字典编码
	DictSort  int         `orm:"dict_sort"         json:"dictSort"`  // 字典排序
	DictLabel string      `orm:"dict_label"        json:"dictLabel"` // 字典标签
	DictValue string      `orm:"dict_value"        json:"dictValue"` // 字典键值
	DictType  string      `orm:"dict_type"         json:"dictType"`  // 字典类型
	CssClass  string      `orm:"css_class"         json:"cssClass"`  // 样式属性（其他样式扩展）
	ListClass string      `orm:"list_class"        json:"listClass"` // 表格回显样式
	IsDefault int         `orm:"is_default"        json:"isDefault"` // 是否默认（1是 0否）
	Status    int         `orm:"status"            json:"status"`    // 状态（0正常 1停用）
	CreateBy  uint64      `orm:"create_by"         json:"createBy"`  // 创建者
	UpdateBy  uint64      `orm:"update_by"         json:"updateBy"`  // 更新者
	Remark    string      `orm:"remark"            json:"remark"`    // 备注
	CreatedAt *gtime.Time `orm:"created_at"        json:"createdAt"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at"        json:"updatedAt"` // 修改时间
	DeletedAt *gtime.Time `orm:"deleted_at"        json:"deletedAt"` // 删除时间
}
