// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// SysUserPost is the golang structure for table sys_user_post.
type SysUserPost struct {
	UserId int64 `orm:"user_id,primary" json:"userId"` // 用户ID
	PostId int64 `orm:"post_id,primary" json:"postId"` // 岗位ID
}
