// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// SysRole is the golang structure for table sys_role.
type SysRole struct {
	Id        uint    `orm:"id,primary"  json:"id"`        //
	Status    uint    `orm:"status"      json:"status"`    // 状态;0:禁用;1:正常
	ListOrder float64 `orm:"list_order"  json:"listOrder"` // 排序
	Name      string  `orm:"name"        json:"name"`      // 角色名称
	Remark    string  `orm:"remark"      json:"remark"`    // 备注
	DataScope uint    `orm:"data_scope"  json:"dataScope"` // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
}
