// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// SysRoleDept is the golang structure for table sys_role_dept.
type SysRoleDept struct {
	RoleId int64 `orm:"role_id,primary" json:"roleId"` // 角色ID
	DeptId int64 `orm:"dept_id,primary" json:"deptId"` // 部门ID
}
