// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysUserOnline is the golang structure for table sys_user_online.
type SysUserOnline struct {
	Id         uint64      `orm:"id,primary"   json:"id"`         //
	Uuid       string      `orm:"uuid"         json:"uuid"`       // 用户标识
	Token      string      `orm:"token,unique" json:"token"`      // 用户token
	CreateTime *gtime.Time `orm:"create_time"  json:"createTime"` // 登录时间
	UserName   string      `orm:"user_name"    json:"userName"`   // 用户名
	Ip         string      `orm:"ip"           json:"ip"`         // 登录ip
	Explorer   string      `orm:"explorer"     json:"explorer"`   // 浏览器
	Os         string      `orm:"os"           json:"os"`         // 操作系统
}
