// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gfast/app/system/model/internal"
)

// SyncSrcTable is the golang structure for table sync_src_table.
type SyncSrcTable internal.SyncSrcTable

// Fill with you ideas below.