// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// SysDept is the golang structure for table sys_dept.
type SysDept struct {
	DeptId    int64       `orm:"dept_id,primary" json:"deptId"`    // 部门id
	ParentId  int64       `orm:"parent_id"       json:"parentId"`  // 父部门id
	Ancestors string      `orm:"ancestors"       json:"ancestors"` // 祖级列表
	DeptName  string      `orm:"dept_name"       json:"deptName"`  // 部门名称
	OrderNum  int         `orm:"order_num"       json:"orderNum"`  // 显示顺序
	Leader    string      `orm:"leader"          json:"leader"`    // 负责人
	Phone     string      `orm:"phone"           json:"phone"`     // 联系电话
	Email     string      `orm:"email"           json:"email"`     // 邮箱
	Status    string      `orm:"status"          json:"status"`    // 部门状态（0正常 1停用）
	CreatedBy uint64      `orm:"created_by"      json:"createdBy"` // 创建人
	UpdatedBy int64       `orm:"updated_by"      json:"updatedBy"` // 修改人
	CreatedAt *gtime.Time `orm:"created_at"      json:"createdAt"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at"      json:"updatedAt"` // 修改时间
	DeletedAt *gtime.Time `orm:"deleted_at"      json:"deletedAt"` // 删除时间
}
