// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gfast/app/system/model/internal"
)

// SysUserPost is the golang structure for table sys_user_post.
type SysUserPost internal.SysUserPost

// Fill with you ideas below.
