// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import "github.com/gogf/gf/frame/g"

// SysWebSet is the golang structure for table sys_web_set.
type SysWebSet struct {
	WebId      int    `orm:"web_id,primary" json:"webId"`      // 主键
	WebContent string `orm:"web_content"    json:"webContent"` // 站点信息
}

// updateReq 用于存储页面更新(新增、修改)网址的信息
type SysWebSetUpdateReq struct {
	WebId      int   `p:"web_id"`
	WebContent g.Map `p:"webContent" v:"required#站点信息不能为空"` // 站点信息
}
