// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gfast/app/system/model/internal"
)

// SysRoleDept is the golang structure for table sys_role_dept.
type SysRoleDept internal.SysRoleDept

// Fill with you ideas below.
