// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"gfast/app/system/model/internal"
)

// SysModelInfo is the golang structure for table sys_model_info.
type SysModelInfo internal.SysModelInfo

// Fill with you ideas below.
