// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// SysPost is the golang structure for table sys_post.
type SysPost struct {
	PostId    int64       `orm:"post_id,primary" json:"postId"`    // 岗位ID
	PostCode  string      `orm:"post_code"       json:"postCode"`  // 岗位编码
	PostName  string      `orm:"post_name"       json:"postName"`  // 岗位名称
	PostSort  int         `orm:"post_sort"       json:"postSort"`  // 显示顺序
	Status    string      `orm:"status"          json:"status"`    // 状态（0正常 1停用）
	Remark    string      `orm:"remark"          json:"remark"`    // 备注
	CreatedBy uint64      `orm:"created_by"      json:"createdBy"` // 创建人
	UpdatedBy uint64      `orm:"updated_by"      json:"updatedBy"` // 修改人
	CreatedAt *gtime.Time `orm:"created_at"      json:"createdAt"` // 创建时间
	UpdatedAt *gtime.Time `orm:"updated_at"      json:"updatedAt"` // 修改时间
	DeletedAt *gtime.Time `orm:"deleted_at"      json:"deletedAt"` // 删除时间
}
