// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

// ToolsGenTableColumn is the golang structure for table tools_gen_table_column.
type ToolsGenTableColumn struct {
	ColumnId         int64  `orm:"column_id,primary" json:"columnId"`          // 编号
	TableId          int64  `orm:"table_id"          json:"tableId"`           // 归属表编号
	ColumnName       string `orm:"column_name"       json:"columnName"`        // 列名称
	ColumnComment    string `orm:"column_comment"    json:"columnComment"`     // 列描述
	ColumnType       string `orm:"column_type"       json:"columnType"`        // 列类型
	GoType           string `orm:"go_type"           json:"goType"`            // Go类型
	GoField          string `orm:"go_field"          json:"goField"`           // Go字段名
	HtmlField        string `orm:"html_field"        json:"htmlField"`         // html字段名
	IsPk             string `orm:"is_pk"             json:"isPk"`              // 是否主键（1是）
	IsIncrement      string `orm:"is_increment"      json:"isIncrement"`       // 是否自增（1是）
	IsRequired       string `orm:"is_required"       json:"isRequired"`        // 是否必填（1是）
	IsInsert         string `orm:"is_insert"         json:"isInsert"`          // 是否为插入字段（1是）
	IsEdit           string `orm:"is_edit"           json:"isEdit"`            // 是否编辑字段（1是）
	IsList           string `orm:"is_list"           json:"isList"`            // 是否列表字段（1是）
	IsQuery          string `orm:"is_query"          json:"isQuery"`           // 是否查询字段（1是）
	QueryType        string `orm:"query_type"        json:"queryType"`         // 查询方式（等于、不等于、大于、小于、范围）
	HtmlType         string `orm:"html_type"         json:"htmlType"`          // 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）
	DictType         string `orm:"dict_type"         json:"dictType"`          // 字典类型
	Sort             int    `orm:"sort"              json:"sort"`              // 排序
	LinkTableName    string `orm:"link_table_name"    json:"linkTableName"`    // 关联表名
	LinkTableClass   string `orm:"link_table_class"   json:"linkTableClass"`   // 关联表类名
	LinkTablePackage string `orm:"link_table_package" json:"linkTablePackage"` // 关联表包名
	LinkLabelId      string `orm:"link_label_id"      json:"linkLabelId"`      // 关联表键名
	LinkLabelName    string `orm:"link_label_name"    json:"linkLabelName"`    // 关联表字段值
}
