// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// ToolsGenTable is the golang structure for table tools_gen_table.
type ToolsGenTable struct {
	TableId        int64       `orm:"table_id,primary"   json:"tableId"`        // 编号
	TableName      string      `orm:"table_name"         json:"tableName"`      // 表名称
	TableComment   string      `orm:"table_comment"      json:"tableComment"`   // 表描述
	ClassName      string      `orm:"class_name"         json:"className"`      // 实体类名称
	TplCategory    string      `orm:"tpl_category"       json:"tplCategory"`    // 使用的模板（crud单表操作 tree树表操作）
	PackageName    string      `orm:"package_name"       json:"packageName"`    // 生成包路径
	ModuleName     string      `orm:"module_name"        json:"moduleName"`     // 生成模块名
	BusinessName   string      `orm:"business_name"      json:"businessName"`   // 生成业务名
	FunctionName   string      `orm:"function_name"      json:"functionName"`   // 生成功能名
	FunctionAuthor string      `orm:"function_author"    json:"functionAuthor"` // 生成功能作者
	Options        string      `orm:"options"            json:"options"`        // 其它生成选项
	CreateTime     *gtime.Time `orm:"create_time"        json:"createTime"`     // 创建时间
	UpdateTime     *gtime.Time `orm:"update_time"        json:"updateTime"`     // 更新时间
	Remark         string      `orm:"remark"             json:"remark"`         // 备注
}
