// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
	ConfigId    uint        `orm:"config_id,primary" json:"configId"`    // 参数主键
	ConfigName  string      `orm:"config_name"       json:"configName"`  // 参数名称
	ConfigKey   string      `orm:"config_key,unique" json:"configKey"`   // 参数键名
	ConfigValue string      `orm:"config_value"      json:"configValue"` // 参数键值
	ConfigType  int         `orm:"config_type"       json:"configType"`  // 系统内置（Y是 N否）
	CreateBy    uint        `orm:"create_by"         json:"createBy"`    // 创建者
	UpdateBy    uint        `orm:"update_by"         json:"updateBy"`    // 更新者
	Remark      string      `orm:"remark"            json:"remark"`      // 备注
	CreatedAt   *gtime.Time `orm:"created_at"        json:"createdAt"`   // 创建时间
	UpdatedAt   *gtime.Time `orm:"updated_at"        json:"updatedAt"`   // 修改时间
	DeletedAt   *gtime.Time `orm:"deleted_at"        json:"deletedAt"`   // 删除时间
}

//分页请求参数
type SysConfigSearchReq struct {
	ConfigName string `p:"configName"` //参数名称
	ConfigKey  string `p:"configKey"`  //参数键名
	ConfigType string `p:"configType"` //状态
	BeginTime  string `p:"beginTime"`  //开始时间
	EndTime    string `p:"endTime"`    //结束时间
	PageReq
}

//新增页面请求参数
type SysConfigAddReq struct {
	ConfigName  string `p:"configName"  v:"required#参数名称不能为空"`
	ConfigKey   string `p:"configKey"  v:"required#参数键名不能为空"`
	ConfigValue string `p:"configValue"  v:"required#参数键值不能为空"`
	ConfigType  int    `p:"configType"    v:"required|in:0,1#系统内置不能为空|系统内置类型只能为0或1"`
	Remark      string `p:"remark"`
	CreateBy    uint64
}

//修改页面请求参数
type SysConfigEditReq struct {
	ConfigId int64 `p:"configId" v:"required|min:1#主键ID不能为空|主键ID参数错误"`
	UpdateBy uint64
	SysConfigAddReq
}
