// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfast/app/system/dao/internal"

	"github.com/gogf/gf/os/gtime"
)

// syncSrcTableDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type syncSrcTableDao struct {
	*internal.SyncSrcTableDao
}

var (
	// SyncSrcTable is globally public accessible object for table sync_src_table operations.
	SyncSrcTable syncSrcTableDao
)

func init() {
	SyncSrcTable = syncSrcTableDao{
		internal.NewSyncSrcTableDao(),
	}
}

// Fill with you ideas below.


type SyncSrcTableParams struct {
	CreateDate *gtime.Time `orm:"create_date" json:"createDate"` //   
    WriteDate  *gtime.Time `orm:"write_date"  json:"writeDate"`  //   
    TaskId     int64       `orm:"task_id"     json:"taskId"`     //   
    DbType     string      `orm:"db_type"     json:"dbType"`     //   
    DbName     string      `orm:"db_name"     json:"dbName"`     //   
    TableName  string      `orm:"table_name"  json:"tableName"`  //   
    PkFiled    string      `orm:"pk_filed"    json:"pkFiled"`    // 
}