// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/system/dao/internal"
)

// sysDictDataDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysDictDataDao struct {
	internal.SysDictDataDao
}

var (
	// SysDictData is globally public accessible object for table sys_dict_data operations.
	SysDictData = sysDictDataDao{
		internal.SysDictData,
	}
)

// Fill with you ideas below.
