// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfast/app/system/dao/internal"
)

// sysWebSetDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sysWebSetDao struct {
	*internal.SysWebSetDao
}

var (
	// SysWebSet is globally public accessible object for table sys_web_set operations.
	SysWebSet sysWebSetDao
)

func init() {
	SysWebSet = sysWebSetDao{
		internal.NewSysWebSetDao(),
	}
}

// Fill with you ideas below.
