// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	comModel "gfast/app/common/model"
	"gfast/app/system/dao/internal"
)

// sysJobDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sysJobDao struct {
	*internal.SysJobDao
}

var (
	// SysJob is globally public accessible object for table sys_job operations.
	SysJob sysJobDao
)

func init() {
	SysJob = sysJobDao{
		internal.NewSysJobDao(),
	}
}

// Fill with you ideas below.

// SysJobSearchReq 分页请求参数
type SysJobSearchReq struct {
	JobName  string `p:"jobName"`  //任务名称
	JobGroup string `p:"jobGroup"` //任务组名
	Status   string `p:"status"`   //状态（0正常 1暂停）
	comModel.PageReq
}

// SysJobAddReq 添加操作请求参数
type SysJobAddReq struct {
	JobName        string `p:"jobName" v:"required#任务名称不能为空"`
	JobParams      string `p:"jobParams"` // 任务参数
	JobGroup       string `p:"jobGroup" `
	InvokeTarget   string `p:"invokeTarget" v:"required#执行方法不能为空"`
	CronExpression string `p:"cronExpression" v:"required#任务表达式不能为空"`
	MisfirePolicy  int    `p:"misfirePolicy"`
	Concurrent     int    `p:"concurrent" `
	Status         int    `p:"status" v:"required#状态（0正常 1暂停）不能为空"`
	Remark         string `p:"remark" `
	CreateBy       uint64
}

// SysJobEditReq 修改操作请求参数
type SysJobEditReq struct {
	JobId int64 `p:"job_id" v:"min:1#任务id不能为空"`
	SysJobAddReq
	UpdateBy uint64
}
