// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gfast/app/system/dao/internal"
)

// sysUserPostDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserPostDao struct {
	internal.SysUserPostDao
}

var (
	// SysUserPost is globally public accessible object for table sys_user_post operations.
	SysUserPost = sysUserPostDao{
		internal.SysUserPost,
	}
)

// Fill with you ideas below.
