// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"gfast/app/system/dao/internal"
	"gfast/app/system/model"
	"github.com/gogf/gf/frame/g"
)

// sysUserOnlineDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysUserOnlineDao struct {
	internal.SysUserOnlineDao
}

var (
	// SysUserOnline is globally public accessible object for table sys_user_online operations.
	SysUserOnline = sysUserOnlineDao{
		internal.SysUserOnline,
	}
)

// Fill with you ideas below.

// SaveOnline 保存登录用户在线状态
func (d sysUserOnlineDao) SaveOnline(params *model.SysUserOnline) {
	//查询是否已存在当前用户
	info, err := d.Fields(d.Columns.Id).FindOne(d.Columns.Token, params.Token)
	if err != nil {
		g.Log().Error(err)
		return
	}
	//若已存在则更新
	if info != nil {
		_, err := SysUserOnline.Where(SysUserOnline.Columns.Id, info.Id).FieldsEx(SysUserOnline.Columns.Id).Update(params)
		if err != nil {
			g.Log().Error(err)
		}
	} else { //否则新增
		_, err := SysUserOnline.FieldsEx(SysUserOnline.Columns.Id).Insert(params)
		if err != nil {
			g.Log().Error(err)
		}
	}
}
