// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	comModel "gfast/app/common/model"
	"gfast/app/system/dao/internal"
	"gfast/app/system/model"
	"github.com/gogf/gf/os/gtime"
)

// toolsGenTableDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type toolsGenTableDao struct {
	*internal.ToolsGenTableDao
}

var (
	// ToolsGenTable is globally public accessible object for table tools_gen_table operations.
	ToolsGenTable toolsGenTableDao
)

func init() {
	ToolsGenTable = toolsGenTableDao{
		internal.NewToolsGenTableDao(),
	}
}

// Fill with you ideas below.

// ToolsGenTableSearchReq 分页请求参数
type ToolsGenTableSearchReq struct {
	TableName    string `p:"tableName"`    //表名称
	TableComment string `p:"tableComment"` //表描述
	comModel.PageReq
}

// ToolsGenTableColumnsRes 表与字段组合数据
type ToolsGenTableColumnsRes struct {
	*model.ToolsGenTable
	Columns []*model.ToolsGenTableColumn `json:"columns"`
}

// ToolsGenTableEditReq 生成信息修改参数
type ToolsGenTableEditReq struct {
	TableId        int64                        `p:"tableId" v:"required#主键ID不能为空"`
	TableName      string                       `p:"tableName"  v:"required#表名称不能为空"`
	TableComment   string                       `p:"tableComment"  v:"required#表描述不能为空"`
	ClassName      string                       `p:"className" v:"required#实体类名称不能为空"`
	FunctionAuthor string                       `p:"functionAuthor"  v:"required#作者不能为空"`
	TplCategory    string                       `p:"tplCategory"`
	PackageName    string                       `p:"packageName" v:"required#生成包路径不能为空"`
	ModuleName     string                       `p:"moduleName" v:"required#生成模块名不能为空"`
	BusinessName   string                       `p:"businessName" v:"required#生成业务名不能为空"`
	FunctionName   string                       `p:"functionName" v:"required#生成功能名不能为空"`
	Remark         string                       `p:"remark"`
	Params         string                       `p:"params"`
	Columns        []*model.ToolsGenTableColumn `p:"columns"`
	TreeCode       string                       `p:"tree_code"`
	TreeParentCode string                       `p:"tree_parent_code"`
	TreeName       string                       `p:"tree_name"`
	UserName       string
}

// ToolsGenTableExtend 实体扩展
type ToolsGenTableExtend struct {
	TableId        int64                        `orm:"table_id,primary" json:"table_id"`        // 编号
	TableName      string                       `orm:"table_name"       json:"table_name"`      // 表名称
	TableComment   string                       `orm:"table_comment"    json:"table_comment"`   // 表描述
	ClassName      string                       `orm:"class_name"       json:"class_name"`      // 实体类名称
	TplCategory    string                       `orm:"tpl_category"     json:"tpl_category"`    // 使用的模板（crud单表操作 tree树表操作）
	PackageName    string                       `orm:"package_name"     json:"package_name"`    // 生成包路径
	ModuleName     string                       `orm:"module_name"      json:"module_name"`     // 生成模块名
	BusinessName   string                       `orm:"business_name"    json:"business_name"`   // 生成业务名
	FunctionName   string                       `orm:"function_name"    json:"function_name"`   // 生成功能名
	FunctionAuthor string                       `orm:"function_author"  json:"function_author"` // 生成功能作者
	Options        string                       `orm:"options"          json:"options"`         // 其它生成选项
	CreateBy       string                       `orm:"create_by"        json:"create_by"`       // 创建者
	CreateTime     *gtime.Time                  `orm:"create_time"      json:"create_time"`     // 创建时间
	UpdateBy       string                       `orm:"update_by"        json:"update_by"`       // 更新者
	UpdateTime     *gtime.Time                  `orm:"update_time"      json:"update_time"`     // 更新时间
	Remark         string                       `orm:"remark"           json:"remark"`          // 备注
	TreeCode       string                       `json:"tree_code"`                              // 树编码字段
	TreeParentCode string                       `json:"tree_parent_code"`                       // 树父编码字段
	TreeName       string                       `json:"tree_name"`                              // 树名称字段
	Columns        []*model.ToolsGenTableColumn `json:"columns"`                                // 表列信息
	PkColumn       *model.ToolsGenTableColumn   `json:"pkColumn"`                               // 主键列信息
}
