// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysWebSetDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysWebSetDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sysWebSetColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// SysWebSetColumns defines and stores column names for table sys_web_set.
type sysWebSetColumns struct {
	WebId      string // 主键
	WebContent string // 站点信息
}

// NewSysWebSetDao creates and returns a new DAO object for table data access.
func NewSysWebSetDao() *SysWebSetDao {
	columns := sysWebSetColumns{
		WebId:      "web_id",
		WebContent: "web_content",
	}
	return &SysWebSetDao{
		C:     columns,
		M:     g.DB("default").Model("sys_web_set").Safe(),
		DB:    g.DB("default"),
		Table: "sys_web_set",
	}
}
