// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysUserPostDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysUserPostDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns sysUserPostColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysUserPostColumns defines and stores column names for table sys_user_post.
type sysUserPostColumns struct {
	UserId string // 用户ID
	PostId string // 岗位ID
}

var (
	// SysUserPost is globally public accessible object for table sys_user_post operations.
	SysUserPost = SysUserPostDao{
		M:     g.DB("default").Model("sys_user_post").Safe(),
		DB:    g.DB("default"),
		Table: "sys_user_post",
		Columns: sysUserPostColumns{
			UserId: "user_id",
			PostId: "post_id",
		},
	}
)
