// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysJobDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysJobDao struct {
	gmvc.M               // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sysJobColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB        // DB is the raw underlying database management object.
	Table  string        // Table is the underlying table name of the DAO.
}

// SysJobColumns defines and stores column names for table sys_job.
type sysJobColumns struct {
	JobId          string // 任务ID
	JobName        string // 任务名称
	JobParams      string // 参数
	JobGroup       string // 任务组名
	InvokeTarget   string // 调用目标字符串
	CronExpression string // cron执行表达式
	MisfirePolicy  string // 计划执行策略（1多次执行 2执行一次）
	Concurrent     string // 是否并发执行（0允许 1禁止）
	Status         string // 状态（0正常 1暂停）
	CreateBy       string // 创建者
	UpdateBy       string // 更新者
	Remark         string // 备注信息
	CreatedAt      string // 创建时间
	UpdatedAt      string // 更新时间
	DeletedAt      string // 删除时间
}

// NewSysJobDao creates and returns a new DAO object for table data access.
func NewSysJobDao() *SysJobDao {
	columns := sysJobColumns{
		JobId:          "job_id",
		JobName:        "job_name",
		JobParams:      "job_params",
		JobGroup:       "job_group",
		InvokeTarget:   "invoke_target",
		CronExpression: "cron_expression",
		MisfirePolicy:  "misfire_policy",
		Concurrent:     "concurrent",
		Status:         "status",
		CreateBy:       "create_by",
		UpdateBy:       "update_by",
		Remark:         "remark",
		CreatedAt:      "created_at",
		UpdatedAt:      "updated_at",
		DeletedAt:      "deleted_at",
	}
	return &SysJobDao{
		C:     columns,
		M:     g.DB("default").Model("sys_job").Safe(),
		DB:    g.DB("default"),
		Table: "sys_job",
	}
}
