// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysConfigDao is the manager for logic model data accessing and custom defined data operations functions management.
type SysConfigDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sysConfigColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// SysConfigColumns defines and stores column names for table sys_config.
type sysConfigColumns struct {
	ConfigId    string // 参数主键
	ConfigName  string // 参数名称
	ConfigKey   string // 参数键名
	ConfigValue string // 参数键值
	ConfigType  string // 系统内置（Y是 N否）
	CreateBy    string // 创建者
	UpdateBy    string // 更新者
	Remark      string // 备注
	CreatedAt   string // 创建时间
	UpdatedAt   string // 修改时间
	DeletedAt   string // 删除时间
}

// NewSysConfigDao creates and returns a new DAO object for table data access.
func NewSysConfigDao() *SysConfigDao {
	columns := sysConfigColumns{
		ConfigId:    "config_id",
		ConfigName:  "config_name",
		ConfigKey:   "config_key",
		ConfigValue: "config_value",
		ConfigType:  "config_type",
		CreateBy:    "create_by",
		UpdateBy:    "update_by",
		Remark:      "remark",
		CreatedAt:   "created_at",
		UpdatedAt:   "updated_at",
		DeletedAt:   "deleted_at",
	}
	return &SysConfigDao{
		C:     columns,
		M:     g.DB("default").Model("sys_config").Safe(),
		DB:    g.DB("default"),
		Table: "sys_config",
	}
}
